[[main]]
  name = "হোম"
  url = ""
  weight = -110

# [[main]]
#   name = "আর্কাইভ"
#   url = "post/rich-content/"
#   weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "লিংকস"
  identifier = "লিংকস"
  weight = -108
[[main]]
  parent = "লিংকস"
  name = "LinkedIn"
  url = "https://www.linkedin.com/"
[[main]]
  parent = "লিংকস"
  name = "Twitter"
  url = "https://twitter.com/"

[[main]]
  name = "আমার সম্পর্কে"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "গিটহাব"
  type = "social"
  weight = 1
  url = "https://github.com/atanuroy911"
[[social]]
  name = "টুইটার"
  weight = 2
  url = "https://twitter.com/atanuroy911"
[[social]]
  name = "লিঙ্কড ইন"
  weight = 3
  url = "https://www.linkedin.com/in/atanu-shuvam-roy"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"